kind: pipeline
name: ci
steps:
- commands:
  - make build
  image: zachfi/build-image
  name: build
  pull: always
- commands:
  - make test
  image: zachfi/build-image
  name: test
  pull: always
- commands:
  - make snapshot
  image: zachfi/build-image
  name: snapshot
  pull: always
- commands:
  - make release
  image: zachfi/build-image
  name: release
  pull: always
  when:
    ref:
    - refs/tags/*
trigger:
  event:
  - push
  ref:
  - refs/heads/**
