---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - make build
  image: reg.dist.svc.cluster.znet:5000/zachfi/tools
  name: build
  pull: always
- commands:
  - make test
  image: reg.dist.svc.cluster.znet:5000/zachfi/tools
  name: test
  pull: always
trigger:
  ref:
  - refs/heads/main
  - refs/heads/dependabot/**
  - refs/tags/v*
---
depends_on: []
kind: pipeline
name: main
steps:
- commands:
  - make snapshot
  image: reg.dist.svc.cluster.znet:5000/zachfi/tools
  name: snapshot
  pull: always
trigger:
  ref:
  - refs/heads/main
---
depends_on: []
kind: pipeline
name: release
steps:
- commands:
  - make release
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  image: reg.dist.svc.cluster.znet:5000/zachfi/tools
  name: release
  pull: always
  when:
    ref:
    - refs/tags/v*
trigger:
  ref:
  - refs/tags/v*
---
kind: signature
hmac: a4e92a688e3663b2ca2a0366567b0f041df4ea8d8e7967d886f24c28dc17992f

...
