---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - make build
  image: zachfi/shell
  name: build
  pull: always
- commands:
  - make test
  image: zachfi/shell
  name: test
  pull: always
- commands:
  - make snapshot
  image: zachfi/shell
  name: snapshot
  pull: always
---
depends_on: []
kind: pipeline
name: release
steps:
- commands:
  - make release
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  image: zachfi/shell
  name: release
  pull: always
  when:
    ref:
    - refs/tags/v*
trigger:
  ref:
  - refs/tags/*
