//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudriereBulkBuild) DeepCopyInto(out *PoudriereBulkBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudriereBulkBuild.
func (in *PoudriereBulkBuild) DeepCopy() *PoudriereBulkBuild {
	if in == nil {
		return nil
	}
	out := new(PoudriereBulkBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoudriereBulkBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudriereBulkBuildList) DeepCopyInto(out *PoudriereBulkBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PoudriereBulkBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudriereBulkBuildList.
func (in *PoudriereBulkBuildList) DeepCopy() *PoudriereBulkBuildList {
	if in == nil {
		return nil
	}
	out := new(PoudriereBulkBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoudriereBulkBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudriereBulkBuildSpec) DeepCopyInto(out *PoudriereBulkBuildSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudriereBulkBuildSpec.
func (in *PoudriereBulkBuildSpec) DeepCopy() *PoudriereBulkBuildSpec {
	if in == nil {
		return nil
	}
	out := new(PoudriereBulkBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudriereBulkBuildStatus) DeepCopyInto(out *PoudriereBulkBuildStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudriereBulkBuildStatus.
func (in *PoudriereBulkBuildStatus) DeepCopy() *PoudriereBulkBuildStatus {
	if in == nil {
		return nil
	}
	out := new(PoudriereBulkBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudriereJail) DeepCopyInto(out *PoudriereJail) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudriereJail.
func (in *PoudriereJail) DeepCopy() *PoudriereJail {
	if in == nil {
		return nil
	}
	out := new(PoudriereJail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoudriereJail) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudriereJailList) DeepCopyInto(out *PoudriereJailList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PoudriereJail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudriereJailList.
func (in *PoudriereJailList) DeepCopy() *PoudriereJailList {
	if in == nil {
		return nil
	}
	out := new(PoudriereJailList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoudriereJailList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudriereJailSpec) DeepCopyInto(out *PoudriereJailSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudriereJailSpec.
func (in *PoudriereJailSpec) DeepCopy() *PoudriereJailSpec {
	if in == nil {
		return nil
	}
	out := new(PoudriereJailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudriereJailStatus) DeepCopyInto(out *PoudriereJailStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudriereJailStatus.
func (in *PoudriereJailStatus) DeepCopy() *PoudriereJailStatus {
	if in == nil {
		return nil
	}
	out := new(PoudriereJailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudrierePortsTree) DeepCopyInto(out *PoudrierePortsTree) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudrierePortsTree.
func (in *PoudrierePortsTree) DeepCopy() *PoudrierePortsTree {
	if in == nil {
		return nil
	}
	out := new(PoudrierePortsTree)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoudrierePortsTree) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudrierePortsTreeList) DeepCopyInto(out *PoudrierePortsTreeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PoudrierePortsTree, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudrierePortsTreeList.
func (in *PoudrierePortsTreeList) DeepCopy() *PoudrierePortsTreeList {
	if in == nil {
		return nil
	}
	out := new(PoudrierePortsTreeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoudrierePortsTreeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudrierePortsTreeSpec) DeepCopyInto(out *PoudrierePortsTreeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudrierePortsTreeSpec.
func (in *PoudrierePortsTreeSpec) DeepCopy() *PoudrierePortsTreeSpec {
	if in == nil {
		return nil
	}
	out := new(PoudrierePortsTreeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoudrierePortsTreeStatus) DeepCopyInto(out *PoudrierePortsTreeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoudrierePortsTreeStatus.
func (in *PoudrierePortsTreeStatus) DeepCopy() *PoudrierePortsTreeStatus {
	if in == nil {
		return nil
	}
	out := new(PoudrierePortsTreeStatus)
	in.DeepCopyInto(out)
	return out
}
