# permissions for end users to edit configsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nodemanager
    app.kubernetes.io/part-of: nodemanager
    app.kubernetes.io/managed-by: kustomize
  name: configset-editor-role
rules:
- apiGroups:
  - common.nodemanager
  resources:
  - configsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - common.nodemanager
  resources:
  - configsets/status
  verbs:
  - get
