# permissions for end users to view poudriereports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: poudriereports-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nodemanager
    app.kubernetes.io/part-of: nodemanager
    app.kubernetes.io/managed-by: kustomize
  name: poudriereports-viewer-role
rules:
- apiGroups:
  - freebsd.nodemanager
  resources:
  - poudriereports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - freebsd.nodemanager
  resources:
  - poudriereports/status
  verbs:
  - get
