---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - common.nodemanager.nodemanager
  resources:
  - configsets
  - managednodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - common.nodemanager.nodemanager
  resources:
  - configsets/finalizers
  - managednodes/finalizers
  verbs:
  - update
- apiGroups:
  - common.nodemanager.nodemanager
  resources:
  - configsets/status
  - managednodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - freebsd.nodemanager
  resources:
  - jails
  - poudrieres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freebsd.nodemanager
  resources:
  - jails/finalizers
  - poudrieres/finalizers
  verbs:
  - update
- apiGroups:
  - freebsd.nodemanager
  resources:
  - jails/status
  - poudrieres/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - pods/eviction
  verbs:
  - create
