apiVersion: freebsd.nodemanager/v1
kind: Jail
metadata:
  labels:
    app.kubernetes.io/name: nodemanager
    app.kubernetes.io/managed-by: kustomize
  name: jail-sample
spec:
  templateRef: standard
  nodeName: myhost.example.com
  release: "14.4-RELEASE"
  inet: "172.16.20.10/27"
  inet6: "2001:db8::10/120"
