# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/common.nodemanager_configsets.yaml
  - bases/common.nodemanager_managednodes.yaml
- bases/freebsd.zachfi_poudrierejails.yaml
- bases/freebsd.zachfi_poudriereportstrees.yaml
- bases/freebsd.zachfi_poudrierebulkbuilds.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_configsets.yaml
#- patches/webhook_in_managednodes.yaml
#- patches/webhook_in_poudrierejails.yaml
#- patches/webhook_in_poudriereportstrees.yaml
#- patches/webhook_in_poudrierebulkbuilds.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_configsets.yaml
#- patches/cainjection_in_managednodes.yaml
#- patches/cainjection_in_poudrierejails.yaml
#- patches/cainjection_in_poudriereportstrees.yaml
#- patches/cainjection_in_poudrierebulkbuilds.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
