// Copyright 2024.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: notification/v1/notification.proto

package notificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeNotificationService_Subscribe_FullMethodName         = "/notification.v1.NodeNotificationService/Subscribe"
	NodeNotificationService_RespondToApproval_FullMethodName = "/notification.v1.NodeNotificationService/RespondToApproval"
)

// NodeNotificationServiceClient is the client API for NodeNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeNotificationService allows a user-space agent to receive notifications
// from the nodemanager daemon and respond to approval requests.
type NodeNotificationServiceClient interface {
	// Subscribe opens a server-streaming connection. The agent identifies itself
	// and receives events for the lifetime of the stream.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// RespondToApproval sends the user's decision for a pending approval request.
	RespondToApproval(ctx context.Context, in *ApprovalResponse, opts ...grpc.CallOption) (*ApprovalResponseAck, error)
}

type nodeNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeNotificationServiceClient(cc grpc.ClientConnInterface) NodeNotificationServiceClient {
	return &nodeNotificationServiceClient{cc}
}

func (c *nodeNotificationServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeNotificationService_ServiceDesc.Streams[0], NodeNotificationService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeNotificationService_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *nodeNotificationServiceClient) RespondToApproval(ctx context.Context, in *ApprovalResponse, opts ...grpc.CallOption) (*ApprovalResponseAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalResponseAck)
	err := c.cc.Invoke(ctx, NodeNotificationService_RespondToApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeNotificationServiceServer is the server API for NodeNotificationService service.
// All implementations must embed UnimplementedNodeNotificationServiceServer
// for forward compatibility.
//
// NodeNotificationService allows a user-space agent to receive notifications
// from the nodemanager daemon and respond to approval requests.
type NodeNotificationServiceServer interface {
	// Subscribe opens a server-streaming connection. The agent identifies itself
	// and receives events for the lifetime of the stream.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	// RespondToApproval sends the user's decision for a pending approval request.
	RespondToApproval(context.Context, *ApprovalResponse) (*ApprovalResponseAck, error)
	mustEmbedUnimplementedNodeNotificationServiceServer()
}

// UnimplementedNodeNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeNotificationServiceServer struct{}

func (UnimplementedNodeNotificationServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedNodeNotificationServiceServer) RespondToApproval(context.Context, *ApprovalResponse) (*ApprovalResponseAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RespondToApproval not implemented")
}
func (UnimplementedNodeNotificationServiceServer) mustEmbedUnimplementedNodeNotificationServiceServer() {
}
func (UnimplementedNodeNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeNodeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeNotificationServiceServer will
// result in compilation errors.
type UnsafeNodeNotificationServiceServer interface {
	mustEmbedUnimplementedNodeNotificationServiceServer()
}

func RegisterNodeNotificationServiceServer(s grpc.ServiceRegistrar, srv NodeNotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeNotificationService_ServiceDesc, srv)
}

func _NodeNotificationService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeNotificationServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeNotificationService_SubscribeServer = grpc.ServerStreamingServer[Event]

func _NodeNotificationService_RespondToApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNotificationServiceServer).RespondToApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeNotificationService_RespondToApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNotificationServiceServer).RespondToApproval(ctx, req.(*ApprovalResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeNotificationService_ServiceDesc is the grpc.ServiceDesc for NodeNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.v1.NodeNotificationService",
	HandlerType: (*NodeNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RespondToApproval",
			Handler:    _NodeNotificationService_RespondToApproval_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _NodeNotificationService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notification/v1/notification.proto",
}
