// Copyright 2024.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApprovalAction int32

const (
	ApprovalAction_APPROVAL_ACTION_UNSPECIFIED ApprovalAction = 0
	ApprovalAction_APPROVAL_ACTION_APPROVE     ApprovalAction = 1
	ApprovalAction_APPROVAL_ACTION_DENY        ApprovalAction = 2
	ApprovalAction_APPROVAL_ACTION_DELAY       ApprovalAction = 3
)

// Enum value maps for ApprovalAction.
var (
	ApprovalAction_name = map[int32]string{
		0: "APPROVAL_ACTION_UNSPECIFIED",
		1: "APPROVAL_ACTION_APPROVE",
		2: "APPROVAL_ACTION_DENY",
		3: "APPROVAL_ACTION_DELAY",
	}
	ApprovalAction_value = map[string]int32{
		"APPROVAL_ACTION_UNSPECIFIED": 0,
		"APPROVAL_ACTION_APPROVE":     1,
		"APPROVAL_ACTION_DENY":        2,
		"APPROVAL_ACTION_DELAY":       3,
	}
)

func (x ApprovalAction) Enum() *ApprovalAction {
	p := new(ApprovalAction)
	*p = x
	return p
}

func (x ApprovalAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalAction) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (ApprovalAction) Type() protoreflect.EnumType {
	return &file_notification_v1_notification_proto_enumTypes[0]
}

func (x ApprovalAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalAction.Descriptor instead.
func (ApprovalAction) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_BackupStarted
	//	*Event_BackupCompleted
	//	*Event_UpgradeApprovalRequest
	//	*Event_UpgradeStarted
	//	*Event_UpgradeCompleted
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetBackupStarted() *BackupStarted {
	if x != nil {
		if x, ok := x.Payload.(*Event_BackupStarted); ok {
			return x.BackupStarted
		}
	}
	return nil
}

func (x *Event) GetBackupCompleted() *BackupCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Event_BackupCompleted); ok {
			return x.BackupCompleted
		}
	}
	return nil
}

func (x *Event) GetUpgradeApprovalRequest() *UpgradeApprovalRequest {
	if x != nil {
		if x, ok := x.Payload.(*Event_UpgradeApprovalRequest); ok {
			return x.UpgradeApprovalRequest
		}
	}
	return nil
}

func (x *Event) GetUpgradeStarted() *UpgradeStarted {
	if x != nil {
		if x, ok := x.Payload.(*Event_UpgradeStarted); ok {
			return x.UpgradeStarted
		}
	}
	return nil
}

func (x *Event) GetUpgradeCompleted() *UpgradeCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Event_UpgradeCompleted); ok {
			return x.UpgradeCompleted
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_BackupStarted struct {
	BackupStarted *BackupStarted `protobuf:"bytes,10,opt,name=backup_started,json=backupStarted,proto3,oneof"`
}

type Event_BackupCompleted struct {
	BackupCompleted *BackupCompleted `protobuf:"bytes,11,opt,name=backup_completed,json=backupCompleted,proto3,oneof"`
}

type Event_UpgradeApprovalRequest struct {
	UpgradeApprovalRequest *UpgradeApprovalRequest `protobuf:"bytes,12,opt,name=upgrade_approval_request,json=upgradeApprovalRequest,proto3,oneof"`
}

type Event_UpgradeStarted struct {
	UpgradeStarted *UpgradeStarted `protobuf:"bytes,13,opt,name=upgrade_started,json=upgradeStarted,proto3,oneof"`
}

type Event_UpgradeCompleted struct {
	UpgradeCompleted *UpgradeCompleted `protobuf:"bytes,14,opt,name=upgrade_completed,json=upgradeCompleted,proto3,oneof"`
}

func (*Event_BackupStarted) isEvent_Payload() {}

func (*Event_BackupCompleted) isEvent_Payload() {}

func (*Event_UpgradeApprovalRequest) isEvent_Payload() {}

func (*Event_UpgradeStarted) isEvent_Payload() {}

func (*Event_UpgradeCompleted) isEvent_Payload() {}

type BackupStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Configset     string                 `protobuf:"bytes,2,opt,name=configset,proto3" json:"configset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupStarted) Reset() {
	*x = BackupStarted{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStarted) ProtoMessage() {}

func (x *BackupStarted) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStarted.ProtoReflect.Descriptor instead.
func (*BackupStarted) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *BackupStarted) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *BackupStarted) GetConfigset() string {
	if x != nil {
		return x.Configset
	}
	return ""
}

type BackupCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FileBackupResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Configset     string                 `protobuf:"bytes,2,opt,name=configset,proto3" json:"configset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCompleted) Reset() {
	*x = BackupCompleted{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCompleted) ProtoMessage() {}

func (x *BackupCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCompleted.ProtoReflect.Descriptor instead.
func (*BackupCompleted) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *BackupCompleted) GetResults() []*FileBackupResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BackupCompleted) GetConfigset() string {
	if x != nil {
		return x.Configset
	}
	return ""
}

type FileBackupResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileBackupResult) Reset() {
	*x = FileBackupResult{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileBackupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBackupResult) ProtoMessage() {}

func (x *FileBackupResult) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBackupResult.ProtoReflect.Descriptor instead.
func (*FileBackupResult) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *FileBackupResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileBackupResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileBackupResult) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FileBackupResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpgradeApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Schedule      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	DefaultAction ApprovalAction         `protobuf:"varint,4,opt,name=default_action,json=defaultAction,proto3,enum=notification.v1.ApprovalAction" json:"default_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeApprovalRequest) Reset() {
	*x = UpgradeApprovalRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeApprovalRequest) ProtoMessage() {}

func (x *UpgradeApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeApprovalRequest.ProtoReflect.Descriptor instead.
func (*UpgradeApprovalRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *UpgradeApprovalRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpgradeApprovalRequest) GetSchedule() *timestamppb.Timestamp {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *UpgradeApprovalRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *UpgradeApprovalRequest) GetDefaultAction() ApprovalAction {
	if x != nil {
		return x.DefaultAction
	}
	return ApprovalAction_APPROVAL_ACTION_UNSPECIFIED
}

type UpgradeStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeStarted) Reset() {
	*x = UpgradeStarted{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeStarted) ProtoMessage() {}

func (x *UpgradeStarted) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeStarted.ProtoReflect.Descriptor instead.
func (*UpgradeStarted) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *UpgradeStarted) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpgradeCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RebootPending bool                   `protobuf:"varint,3,opt,name=reboot_pending,json=rebootPending,proto3" json:"reboot_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCompleted) Reset() {
	*x = UpgradeCompleted{}
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCompleted) ProtoMessage() {}

func (x *UpgradeCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCompleted.ProtoReflect.Descriptor instead.
func (*UpgradeCompleted) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *UpgradeCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpgradeCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpgradeCompleted) GetRebootPending() bool {
	if x != nil {
		return x.RebootPending
	}
	return false
}

type ApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Action        ApprovalAction         `protobuf:"varint,2,opt,name=action,proto3,enum=notification.v1.ApprovalAction" json:"action,omitempty"`
	DelayDuration *durationpb.Duration   `protobuf:"bytes,3,opt,name=delay_duration,json=delayDuration,proto3" json:"delay_duration,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalResponse) Reset() {
	*x = ApprovalResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResponse) ProtoMessage() {}

func (x *ApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResponse.ProtoReflect.Descriptor instead.
func (*ApprovalResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *ApprovalResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ApprovalResponse) GetAction() ApprovalAction {
	if x != nil {
		return x.Action
	}
	return ApprovalAction_APPROVAL_ACTION_UNSPECIFIED
}

func (x *ApprovalResponse) GetDelayDuration() *durationpb.Duration {
	if x != nil {
		return x.DelayDuration
	}
	return nil
}

func (x *ApprovalResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ApprovalResponseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalResponseAck) Reset() {
	*x = ApprovalResponseAck{}
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResponseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResponseAck) ProtoMessage() {}

func (x *ApprovalResponseAck) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResponseAck.ProtoReflect.Descriptor instead.
func (*ApprovalResponseAck) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *ApprovalResponseAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ApprovalResponseAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x0fnotification.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x10SubscribeRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xf7\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12G\n" +
	"\x0ebackup_started\x18\n" +
	" \x01(\v2\x1e.notification.v1.BackupStartedH\x00R\rbackupStarted\x12M\n" +
	"\x10backup_completed\x18\v \x01(\v2 .notification.v1.BackupCompletedH\x00R\x0fbackupCompleted\x12c\n" +
	"\x18upgrade_approval_request\x18\f \x01(\v2'.notification.v1.UpgradeApprovalRequestH\x00R\x16upgradeApprovalRequest\x12J\n" +
	"\x0fupgrade_started\x18\r \x01(\v2\x1f.notification.v1.UpgradeStartedH\x00R\x0eupgradeStarted\x12P\n" +
	"\x11upgrade_completed\x18\x0e \x01(\v2!.notification.v1.UpgradeCompletedH\x00R\x10upgradeCompletedB\t\n" +
	"\apayload\"C\n" +
	"\rBackupStarted\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\x12\x1c\n" +
	"\tconfigset\x18\x02 \x01(\tR\tconfigset\"l\n" +
	"\x0fBackupCompleted\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.notification.v1.FileBackupResultR\aresults\x12\x1c\n" +
	"\tconfigset\x18\x02 \x01(\tR\tconfigset\"n\n" +
	"\x10FileBackupResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xf2\x01\n" +
	"\x16UpgradeApprovalRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x126\n" +
	"\bschedule\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bschedule\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12F\n" +
	"\x0edefault_action\x18\x04 \x01(\x0e2\x1f.notification.v1.ApprovalActionR\rdefaultAction\"2\n" +
	"\x0eUpgradeStarted\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"i\n" +
	"\x10UpgradeCompleted\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0ereboot_pending\x18\x03 \x01(\bR\rrebootPending\"\xbc\x01\n" +
	"\x10ApprovalResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x127\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1f.notification.v1.ApprovalActionR\x06action\x12@\n" +
	"\x0edelay_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rdelayDuration\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"I\n" +
	"\x13ApprovalResponseAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\x83\x01\n" +
	"\x0eApprovalAction\x12\x1f\n" +
	"\x1bAPPROVAL_ACTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17APPROVAL_ACTION_APPROVE\x10\x01\x12\x18\n" +
	"\x14APPROVAL_ACTION_DENY\x10\x02\x12\x19\n" +
	"\x15APPROVAL_ACTION_DELAY\x10\x032\xc1\x01\n" +
	"\x17NodeNotificationService\x12H\n" +
	"\tSubscribe\x12!.notification.v1.SubscribeRequest\x1a\x16.notification.v1.Event0\x01\x12\\\n" +
	"\x11RespondToApproval\x12!.notification.v1.ApprovalResponse\x1a$.notification.v1.ApprovalResponseAckBBZ@github.com/zachfi/nodemanager/pkg/notification/v1;notificationv1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_notification_v1_notification_proto_goTypes = []any{
	(ApprovalAction)(0),            // 0: notification.v1.ApprovalAction
	(*SubscribeRequest)(nil),       // 1: notification.v1.SubscribeRequest
	(*Event)(nil),                  // 2: notification.v1.Event
	(*BackupStarted)(nil),          // 3: notification.v1.BackupStarted
	(*BackupCompleted)(nil),        // 4: notification.v1.BackupCompleted
	(*FileBackupResult)(nil),       // 5: notification.v1.FileBackupResult
	(*UpgradeApprovalRequest)(nil), // 6: notification.v1.UpgradeApprovalRequest
	(*UpgradeStarted)(nil),         // 7: notification.v1.UpgradeStarted
	(*UpgradeCompleted)(nil),       // 8: notification.v1.UpgradeCompleted
	(*ApprovalResponse)(nil),       // 9: notification.v1.ApprovalResponse
	(*ApprovalResponseAck)(nil),    // 10: notification.v1.ApprovalResponseAck
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 12: google.protobuf.Duration
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	11, // 0: notification.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 1: notification.v1.Event.backup_started:type_name -> notification.v1.BackupStarted
	4,  // 2: notification.v1.Event.backup_completed:type_name -> notification.v1.BackupCompleted
	6,  // 3: notification.v1.Event.upgrade_approval_request:type_name -> notification.v1.UpgradeApprovalRequest
	7,  // 4: notification.v1.Event.upgrade_started:type_name -> notification.v1.UpgradeStarted
	8,  // 5: notification.v1.Event.upgrade_completed:type_name -> notification.v1.UpgradeCompleted
	5,  // 6: notification.v1.BackupCompleted.results:type_name -> notification.v1.FileBackupResult
	11, // 7: notification.v1.UpgradeApprovalRequest.schedule:type_name -> google.protobuf.Timestamp
	11, // 8: notification.v1.UpgradeApprovalRequest.deadline:type_name -> google.protobuf.Timestamp
	0,  // 9: notification.v1.UpgradeApprovalRequest.default_action:type_name -> notification.v1.ApprovalAction
	0,  // 10: notification.v1.ApprovalResponse.action:type_name -> notification.v1.ApprovalAction
	12, // 11: notification.v1.ApprovalResponse.delay_duration:type_name -> google.protobuf.Duration
	1,  // 12: notification.v1.NodeNotificationService.Subscribe:input_type -> notification.v1.SubscribeRequest
	9,  // 13: notification.v1.NodeNotificationService.RespondToApproval:input_type -> notification.v1.ApprovalResponse
	2,  // 14: notification.v1.NodeNotificationService.Subscribe:output_type -> notification.v1.Event
	10, // 15: notification.v1.NodeNotificationService.RespondToApproval:output_type -> notification.v1.ApprovalResponseAck
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	file_notification_v1_notification_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_BackupStarted)(nil),
		(*Event_BackupCompleted)(nil),
		(*Event_UpgradeApprovalRequest)(nil),
		(*Event_UpgradeStarted)(nil),
		(*Event_UpgradeCompleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
