// Copyright 2024.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_ERROR       Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_ERROR":       3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_notification_v1_notification_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

type ApprovalAction int32

const (
	ApprovalAction_APPROVAL_ACTION_UNSPECIFIED ApprovalAction = 0
	ApprovalAction_APPROVAL_ACTION_APPROVE     ApprovalAction = 1
	ApprovalAction_APPROVAL_ACTION_DENY        ApprovalAction = 2
	ApprovalAction_APPROVAL_ACTION_DELAY       ApprovalAction = 3
)

// Enum value maps for ApprovalAction.
var (
	ApprovalAction_name = map[int32]string{
		0: "APPROVAL_ACTION_UNSPECIFIED",
		1: "APPROVAL_ACTION_APPROVE",
		2: "APPROVAL_ACTION_DENY",
		3: "APPROVAL_ACTION_DELAY",
	}
	ApprovalAction_value = map[string]int32{
		"APPROVAL_ACTION_UNSPECIFIED": 0,
		"APPROVAL_ACTION_APPROVE":     1,
		"APPROVAL_ACTION_DENY":        2,
		"APPROVAL_ACTION_DELAY":       3,
	}
)

func (x ApprovalAction) Enum() *ApprovalAction {
	p := new(ApprovalAction)
	*p = x
	return p
}

func (x ApprovalAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalAction) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_notification_proto_enumTypes[1].Descriptor()
}

func (ApprovalAction) Type() protoreflect.EnumType {
	return &file_notification_v1_notification_proto_enumTypes[1]
}

func (x ApprovalAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalAction.Descriptor instead.
func (ApprovalAction) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Notification
	//	*Event_UpgradeApprovalRequest
	//	*Event_UpgradeStarted
	//	*Event_UpgradeCompleted
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetNotification() *Notification {
	if x != nil {
		if x, ok := x.Payload.(*Event_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

func (x *Event) GetUpgradeApprovalRequest() *UpgradeApprovalRequest {
	if x != nil {
		if x, ok := x.Payload.(*Event_UpgradeApprovalRequest); ok {
			return x.UpgradeApprovalRequest
		}
	}
	return nil
}

func (x *Event) GetUpgradeStarted() *UpgradeStarted {
	if x != nil {
		if x, ok := x.Payload.(*Event_UpgradeStarted); ok {
			return x.UpgradeStarted
		}
	}
	return nil
}

func (x *Event) GetUpgradeCompleted() *UpgradeCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Event_UpgradeCompleted); ok {
			return x.UpgradeCompleted
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Notification struct {
	Notification *Notification `protobuf:"bytes,10,opt,name=notification,proto3,oneof"`
}

type Event_UpgradeApprovalRequest struct {
	UpgradeApprovalRequest *UpgradeApprovalRequest `protobuf:"bytes,12,opt,name=upgrade_approval_request,json=upgradeApprovalRequest,proto3,oneof"`
}

type Event_UpgradeStarted struct {
	UpgradeStarted *UpgradeStarted `protobuf:"bytes,13,opt,name=upgrade_started,json=upgradeStarted,proto3,oneof"`
}

type Event_UpgradeCompleted struct {
	UpgradeCompleted *UpgradeCompleted `protobuf:"bytes,14,opt,name=upgrade_completed,json=upgradeCompleted,proto3,oneof"`
}

func (*Event_Notification) isEvent_Payload() {}

func (*Event_UpgradeApprovalRequest) isEvent_Payload() {}

func (*Event_UpgradeStarted) isEvent_Payload() {}

func (*Event_UpgradeCompleted) isEvent_Payload() {}

// Notification is a generic user-facing message. External scripts send these
// via SendNotification; the agent displays them as desktop notifications.
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Severity      Severity               `protobuf:"varint,3,opt,name=severity,proto3,enum=notification.v1.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

type NotificationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationAck) Reset() {
	*x = NotificationAck{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationAck) ProtoMessage() {}

func (x *NotificationAck) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationAck.ProtoReflect.Descriptor instead.
func (*NotificationAck) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type UpgradeApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Schedule      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	DefaultAction ApprovalAction         `protobuf:"varint,4,opt,name=default_action,json=defaultAction,proto3,enum=notification.v1.ApprovalAction" json:"default_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeApprovalRequest) Reset() {
	*x = UpgradeApprovalRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeApprovalRequest) ProtoMessage() {}

func (x *UpgradeApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeApprovalRequest.ProtoReflect.Descriptor instead.
func (*UpgradeApprovalRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *UpgradeApprovalRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpgradeApprovalRequest) GetSchedule() *timestamppb.Timestamp {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *UpgradeApprovalRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *UpgradeApprovalRequest) GetDefaultAction() ApprovalAction {
	if x != nil {
		return x.DefaultAction
	}
	return ApprovalAction_APPROVAL_ACTION_UNSPECIFIED
}

type UpgradeStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeStarted) Reset() {
	*x = UpgradeStarted{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeStarted) ProtoMessage() {}

func (x *UpgradeStarted) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeStarted.ProtoReflect.Descriptor instead.
func (*UpgradeStarted) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *UpgradeStarted) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpgradeCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RebootPending bool                   `protobuf:"varint,3,opt,name=reboot_pending,json=rebootPending,proto3" json:"reboot_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCompleted) Reset() {
	*x = UpgradeCompleted{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCompleted) ProtoMessage() {}

func (x *UpgradeCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCompleted.ProtoReflect.Descriptor instead.
func (*UpgradeCompleted) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *UpgradeCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpgradeCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpgradeCompleted) GetRebootPending() bool {
	if x != nil {
		return x.RebootPending
	}
	return false
}

type ApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Action        ApprovalAction         `protobuf:"varint,2,opt,name=action,proto3,enum=notification.v1.ApprovalAction" json:"action,omitempty"`
	DelayDuration *durationpb.Duration   `protobuf:"bytes,3,opt,name=delay_duration,json=delayDuration,proto3" json:"delay_duration,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalResponse) Reset() {
	*x = ApprovalResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResponse) ProtoMessage() {}

func (x *ApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResponse.ProtoReflect.Descriptor instead.
func (*ApprovalResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ApprovalResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ApprovalResponse) GetAction() ApprovalAction {
	if x != nil {
		return x.Action
	}
	return ApprovalAction_APPROVAL_ACTION_UNSPECIFIED
}

func (x *ApprovalResponse) GetDelayDuration() *durationpb.Duration {
	if x != nil {
		return x.DelayDuration
	}
	return nil
}

func (x *ApprovalResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ApprovalResponseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalResponseAck) Reset() {
	*x = ApprovalResponseAck{}
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResponseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResponseAck) ProtoMessage() {}

func (x *ApprovalResponseAck) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResponseAck.ProtoReflect.Descriptor instead.
func (*ApprovalResponseAck) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *ApprovalResponseAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ApprovalResponseAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x0fnotification.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x10SubscribeRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xa4\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12C\n" +
	"\fnotification\x18\n" +
	" \x01(\v2\x1d.notification.v1.NotificationH\x00R\fnotification\x12c\n" +
	"\x18upgrade_approval_request\x18\f \x01(\v2'.notification.v1.UpgradeApprovalRequestH\x00R\x16upgradeApprovalRequest\x12J\n" +
	"\x0fupgrade_started\x18\r \x01(\v2\x1f.notification.v1.UpgradeStartedH\x00R\x0eupgradeStarted\x12P\n" +
	"\x11upgrade_completed\x18\x0e \x01(\v2!.notification.v1.UpgradeCompletedH\x00R\x10upgradeCompletedB\t\n" +
	"\apayload\"o\n" +
	"\fNotification\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x125\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x19.notification.v1.SeverityR\bseverity\"-\n" +
	"\x0fNotificationAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xf2\x01\n" +
	"\x16UpgradeApprovalRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x126\n" +
	"\bschedule\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bschedule\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12F\n" +
	"\x0edefault_action\x18\x04 \x01(\x0e2\x1f.notification.v1.ApprovalActionR\rdefaultAction\"2\n" +
	"\x0eUpgradeStarted\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"i\n" +
	"\x10UpgradeCompleted\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0ereboot_pending\x18\x03 \x01(\bR\rrebootPending\"\xbc\x01\n" +
	"\x10ApprovalResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x127\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1f.notification.v1.ApprovalActionR\x06action\x12@\n" +
	"\x0edelay_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rdelayDuration\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"I\n" +
	"\x13ApprovalResponseAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*a\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x03*\x83\x01\n" +
	"\x0eApprovalAction\x12\x1f\n" +
	"\x1bAPPROVAL_ACTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17APPROVAL_ACTION_APPROVE\x10\x01\x12\x18\n" +
	"\x14APPROVAL_ACTION_DENY\x10\x02\x12\x19\n" +
	"\x15APPROVAL_ACTION_DELAY\x10\x032\x96\x02\n" +
	"\x17NodeNotificationService\x12H\n" +
	"\tSubscribe\x12!.notification.v1.SubscribeRequest\x1a\x16.notification.v1.Event0\x01\x12\\\n" +
	"\x11RespondToApproval\x12!.notification.v1.ApprovalResponse\x1a$.notification.v1.ApprovalResponseAck\x12S\n" +
	"\x10SendNotification\x12\x1d.notification.v1.Notification\x1a .notification.v1.NotificationAckBBZ@github.com/zachfi/nodemanager/pkg/notification/v1;notificationv1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_notification_v1_notification_proto_goTypes = []any{
	(Severity)(0),                  // 0: notification.v1.Severity
	(ApprovalAction)(0),            // 1: notification.v1.ApprovalAction
	(*SubscribeRequest)(nil),       // 2: notification.v1.SubscribeRequest
	(*Event)(nil),                  // 3: notification.v1.Event
	(*Notification)(nil),           // 4: notification.v1.Notification
	(*NotificationAck)(nil),        // 5: notification.v1.NotificationAck
	(*UpgradeApprovalRequest)(nil), // 6: notification.v1.UpgradeApprovalRequest
	(*UpgradeStarted)(nil),         // 7: notification.v1.UpgradeStarted
	(*UpgradeCompleted)(nil),       // 8: notification.v1.UpgradeCompleted
	(*ApprovalResponse)(nil),       // 9: notification.v1.ApprovalResponse
	(*ApprovalResponseAck)(nil),    // 10: notification.v1.ApprovalResponseAck
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 12: google.protobuf.Duration
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	11, // 0: notification.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 1: notification.v1.Event.notification:type_name -> notification.v1.Notification
	6,  // 2: notification.v1.Event.upgrade_approval_request:type_name -> notification.v1.UpgradeApprovalRequest
	7,  // 3: notification.v1.Event.upgrade_started:type_name -> notification.v1.UpgradeStarted
	8,  // 4: notification.v1.Event.upgrade_completed:type_name -> notification.v1.UpgradeCompleted
	0,  // 5: notification.v1.Notification.severity:type_name -> notification.v1.Severity
	11, // 6: notification.v1.UpgradeApprovalRequest.schedule:type_name -> google.protobuf.Timestamp
	11, // 7: notification.v1.UpgradeApprovalRequest.deadline:type_name -> google.protobuf.Timestamp
	1,  // 8: notification.v1.UpgradeApprovalRequest.default_action:type_name -> notification.v1.ApprovalAction
	1,  // 9: notification.v1.ApprovalResponse.action:type_name -> notification.v1.ApprovalAction
	12, // 10: notification.v1.ApprovalResponse.delay_duration:type_name -> google.protobuf.Duration
	2,  // 11: notification.v1.NodeNotificationService.Subscribe:input_type -> notification.v1.SubscribeRequest
	9,  // 12: notification.v1.NodeNotificationService.RespondToApproval:input_type -> notification.v1.ApprovalResponse
	4,  // 13: notification.v1.NodeNotificationService.SendNotification:input_type -> notification.v1.Notification
	3,  // 14: notification.v1.NodeNotificationService.Subscribe:output_type -> notification.v1.Event
	10, // 15: notification.v1.NodeNotificationService.RespondToApproval:output_type -> notification.v1.ApprovalResponseAck
	5,  // 16: notification.v1.NodeNotificationService.SendNotification:output_type -> notification.v1.NotificationAck
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	file_notification_v1_notification_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_Notification)(nil),
		(*Event_UpgradeApprovalRequest)(nil),
		(*Event_UpgradeStarted)(nil),
		(*Event_UpgradeCompleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
